import CompactForm from './CompactForm';
import { InsuranceArt, AdviserArt } from './Artwork';
import './health.css';
export default function HealthPage(){return <main className="health-page" data-page-id="aa0003">
 <section className="health-hero"><div className="health-wrap hero-layout"><div className="hero-copy"><p className="hero-ribbon">큰돈 드는 3대 질환</p><p className="hero-subline">실비보험만으로는 역부족!</p><h1><strong>필수 건강보험</strong><span>나에게 꼭 맞는</span>합리적 상품은?</h1></div><InsuranceArt/></div></section>
 <div className="health-wrap form-position"><CompactForm/></div>
 <section className="health-stat health-wrap"><p className="section-eyebrow">통계청 자료 참고</p><h2>2020년 주요 <em>사망원인 3대 질병</em></h2><div className="stat-layout"><div className="stat-bars"><small>사망률, 단위: 명 (인구 10만 명당)</small>{[{rank:'1위',name:'암',value:160.1,width:100},{rank:'2위',name:'심장질환',value:63,width:39.4},{rank:'4위',name:'뇌혈관질환',value:42.6,width:26.6}].map((r,i)=><div className={`stat-row stat-row-${i}`} key={r.name}><span style={{width:`${r.width}%`}}>{r.rank}</span><strong>{r.name}</strong><b>{r.value}</b></div>)}</div><div className="stat-message"><div className="organ-icons" aria-hidden="true"><span>♡</span><span>♧</span><span>◎</span></div><p>꼭 치료해야 하는 3대 질병!</p><strong>건강보험은 선택 아닌 필수!</strong></div></div></section>
 <section className="health-coverage"><div className="health-wrap"><h2><em className="blue">진단/치료비</em>는 기본!</h2><p className="section-description"><span>질병/상해 입원비, 수술비, 간병비까지</span> 꼼꼼하게 보장받으세요!</p><div className="coverage-card"><span className="question-mark" aria-hidden="true">?</span><ul><li><em>응급실 내원비</em>도 보장해주는 상품은?</li><li><em>입원 첫날부터</em> 보장하는 상품은?!</li><li><em>동네 병원, 한방병원까지</em> 입원일당 보장하는 상품은?</li><li><em>진단비 / 수술비 / 입원비까지 한번에</em> 보장하는 상품은?</li><li><em>상해 / 질병 수술비</em>까지 보장하는 상품은?</li></ul><AdviserArt/><span className="exclamation" aria-hidden="true">!</span></div></div></section>
 <section className="health-expert"><div className="health-wrap"><h2><em>건강보험 전문가</em>가</h2><p className="expert-subtitle">속 시원하게 상담해드립니다!</p><p className="expert-note">고객님의 상황을 고려하여 <strong>13개사 보험사의 다양한 상품</strong>을<br/>한눈에 비교상담해드립니다!</p><div className="expert-bottom"><div className="expert-circles"><span>월<br/>보험료는?</span><span>보장<br/>금액은?</span><span>상품<br/>설계는?</span></div><div className="expert-people"><AdviserArt/></div></div></div></section>
 <section className="health-budget"><div className="health-wrap"><h2>100세 시대! 납입할 보험금이 <em>부담</em>된다면?</h2><p>고객님의 상황에 맞는 스마트한 보험가입으로<br/><strong>보험료 부담을 줄이고 실속은 더하세요!</strong></p><div className="budget-layout"><ul>{['갱신형','비갱신형','순수보장형','납입 면제형','중도해지 환급금 지급형','납입 후 50% 해지환급금 지급형'].map(v=><li key={v}>{v}</li>)}<li aria-hidden="true">•••</li></ul><InsuranceArt warm/></div><p className="budget-end">고객님의 상황에 맞게 <em>부담없는 선택</em>을 하실 수 있도록 도와드립니다!</p></div></section>
 <a className="health-bottom-cta" href="#consult">나에게 꼭 맞는 건강보험 <span>전문가에게 1:1 맞춤상담</span> 받으세요 <b aria-hidden="true">›</b></a>
 </main>}
